apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    app: web-apache
    tier: frontend
spec:
  type: NodePort
  ports:
   - port: 80
     targetPort: 80
     nodePort: 80
  selector:
    matchLabels:
       app: web-apache
       tier: frontend
